def print_guide():
    print("OpenCV Rubik Solver")
    print("Press U R F D L B to store each face")
    print()
    print("1) Hold GREEN face toward camera, WHITE on top. Press F")
    print("2) Rotate right, RED faces camera. Press R")
    print("3) Rotate right, BLUE faces camera. Press B")
    print("4) Rotate right, ORANGE faces camera. Press L")
    print("5) Return GREEN to front, rotate up so WHITE faces camera. Press U")
    print("6) Rotate down so YELLOW faces camera. Press D")
    print("After all 6 faces are stored, press S to solve.")
    print()

def print_move_manual():
    print("\n=== MOVE MANUAL ===")
    print("R  = Turn Right face clockwise")
    print("R' = Turn Right face counter-clockwise")
    print("R2 = Turn Right face 180 degrees")
    print()
    print("L  = Turn Left face clockwise")
    print("L' = Turn Left face counter-clockwise")
    print("L2 = Turn Left face 180 degrees")
    print()
    print("U  = Turn Top face clockwise")
    print("U' = Turn Top face counter-clockwise")
    print("U2 = Turn Top face 180 degrees")
    print()
    print("D  = Turn Bottom face clockwise")
    print("D' = Turn Bottom face counter-clockwise")
    print("D2 = Turn Bottom face 180 degrees")
    print()
    print("F  = Turn Front face clockwise")
    print("F' = Turn Front face counter-clockwise")
    print("F2 = Turn Front face 180 degrees")
    print()
    print("B  = Turn Back face clockwise")
    print("B' = Turn Back face counter-clockwise")
    print("B2 = Turn Back face 180 degrees")
    print("====================\n")